### ISSUE TITLE
Send to multiple telegram contacts

### ISSUE THREAD

**Issue by beastarman74** [atheisthax/mail_to_telegram#2]
I am currently struggling to send an email to multiple telegram contacts. It only sends to the first chat_id.

I have tried the following formats in the config.py (where chatid1 and 2 are the respective chat_id numbers):

chat_id = 'chat_id1,chat_id2'
chat_id = "chat_id1,chat_id2"
chat_id = "chat_id1;chat_id2"

Is it possible to do this?  if so, can you assist me with the config/formatting required please.

If it's not possible currently can I add a feature request for the capability please?

**Comment by atheisthax** [comment]
You can do it via telegram channels

**Comment by beastarman74** [comment]
I've switched to sending to a channel instead, works fine, thanks.
